### PR TITLE
Add SASS & Restyle Sidebar to improve font and give color options. 

### PR DESCRIPTION
**Pull request by DJRHails**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a feature/bugfix branch** (right side). Don't request from master!
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### Description
Screenshot 2019-11-05 at 13 35 35
Screenshot 2019-11-05 at 13 32 57
Screenshot 2019-11-05 at 13 32 45
Screenshot 2019-11-05 at 13 32 31
Screenshot 2019-11-05 at 13 32 14
Screenshot 2019-11-05 at 13 31 55
Screenshot 2019-11-05 at 13 31 32

### Checklist
* [x] Have you done your changes on a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-loop` or `feature/pr-templates`.
* [x] Have you got descriptive commit messages that would make sense if prefixed with "This commit will ..."
* [x] Will you squash when you merge this PR?

💔Thank you!

### CODE REVIEW

**Review by felination — CHANGES_REQUESTED** [review]
Requests tab seems poorly named: hard to be succinct and describe that it is both an ARR log and a list of all artworks that are new to the system? Either find a better name or split these tabs.

**Comment by JamesDalboth** [comment]
The height and width form elements seems to have been rendered strangely.

**Comment by DJRHails** [comment]
Probably the smart move into separate them

**Comment by felination** [comment]
The merge conflict is a result of the RegisterArtistView, so when somebody chooses to finish this PR + fix that conflict, remember to add a link to this view on the sidebar

**Review by felination — APPROVED** [review]

**Review by felination — APPROVED** [review]

**Pull request merged**
